spring:
  application:
    name: eureka-server
server:
  port: 8761
#安全认证配置
security:
  basic:
    enabled: false
  user:
    name: admin  # 用户名
    password: admin123   # 用户密码
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false