apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    run: eureka-server
  namespace: microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: dolphintwo/eureka-server
        ports:
        - containerPort: 8761
          protocol: TCP

kind: Service
apiVersion: v1
metadata:
  name: eureka-server
  labels:
    name: eureka-server
  namespace: microservice
spec:
  selector:
    run: eureka-server
  ports:
  - name: port1
    protocol: TCP
    port: 8761
    targetPort: 8761
  type: NodePort